import type { Metadata } from "next";
import "./../globals.css";

export const metadata: Metadata = {
  title: "Ticket.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-800/95 text-gray-50">{children}</body>
    </html>
  );
}
